[tool.poetry]
name = "k8s-lab"
version = "0.1.0"
description = ""
authors = ["Kevin Chan <kevin@chaster.net>"]
license = "mit"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ansible = "^9.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
