---
version: 3

vars:
  VENV_PYTHON: .venv/bin/python

tasks:
  py:init:
    cmds:
      - poetry install --no-root
  ansible:ping:
    dir: ansible
    cmds:
      - poetry run ansible hosts -m ping -i inventory.ini --user k3s
  pkr:alpine:
    cmds:
      - packer build packer/alpine
  pkr:clean:
    cmds:
      - if [[ -d './bin/images' ]]; then rm -r ./bin/images; fi
  tf:init:
    dir: ./terraform
    cmds:
      - terraform init
  tf:fmt:
    dir: ./terraform
    cmds:
      - terraform fmt --recursive
  tf:show:
    aliases: [ tf:s, tfs ]
    dir: ./terraform
    cmds:
      - task: tf:init
      - terraform show
  tf:plan:
    aliases: [ tf:p, tfp ]
    dir: ./terraform
    cmds:
      - task: tf:init
      - terraform plan
  tf:apply:
    aliases: [ tf:a, tfa ]
    dir: ./terraform
    cmds:
      - task: tf:init
      - terraform apply --auto-approve
  tf:destroy:
    aliases: [ tf:d, tfd ]
    dir: ./terraform
    cmds:
      - task: tf:init
      - terraform destroy --auto-approve
  run:
    cmds:
      - task: mise:init
      - task: py:init
      - task: pkr:clean
      - task: pkr:alpine
      - task: tf:apply
